// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2jBdOaJ2HGSV8ycWE1xMU0UigRM2JMug',
    appId: '1:17508847403:web:a8c47e290b7cae8a2b3f6e',
    messagingSenderId: '17508847403',
    projectId: 'userintegration-f8858',
    authDomain: 'userintegration-f8858.firebaseapp.com',
    databaseURL: 'https://userintegration-f8858-default-rtdb.firebaseio.com',
    storageBucket: 'userintegration-f8858.appspot.com',
    measurementId: 'G-3MTF2V6JCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUbu_aVzBeWAxPHwAljmTnLFUNXqz2F30',
    appId: '1:17508847403:android:e6231d1812d649962b3f6e',
    messagingSenderId: '17508847403',
    projectId: 'userintegration-f8858',
    databaseURL: 'https://userintegration-f8858-default-rtdb.firebaseio.com',
    storageBucket: 'userintegration-f8858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKguveeNZ6FMoIFlr1wTTDFgh8bStqL3A',
    appId: '1:17508847403:ios:9af2362d21b6fc7d2b3f6e',
    messagingSenderId: '17508847403',
    projectId: 'userintegration-f8858',
    databaseURL: 'https://userintegration-f8858-default-rtdb.firebaseio.com',
    storageBucket: 'userintegration-f8858.appspot.com',
    androidClientId: '17508847403-4dj639i7dmfgvrahh83rtrmakojrl47g.apps.googleusercontent.com',
    iosClientId: '17508847403-0k0b7gcgujo55jkr9f5ui4c88rqsh54c.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKguveeNZ6FMoIFlr1wTTDFgh8bStqL3A',
    appId: '1:17508847403:ios:e9cf0627c67855ca2b3f6e',
    messagingSenderId: '17508847403',
    projectId: 'userintegration-f8858',
    databaseURL: 'https://userintegration-f8858-default-rtdb.firebaseio.com',
    storageBucket: 'userintegration-f8858.appspot.com',
    androidClientId: '17508847403-4dj639i7dmfgvrahh83rtrmakojrl47g.apps.googleusercontent.com',
    iosClientId: '17508847403-bmcr472k7t3q8eiu1is1nl05kp7ijf48.apps.googleusercontent.com',
    iosBundleId: 'app.example.userAuth',
  );
}
